export const PAINTING_LIST_REQUEST = 'PAINTING_LIST_REQUEST'
export const PAINTING_LIST_SUCCESS = 'PAINTING_LIST_SUCCESS'
export const PAINTING_LIST_FAIL = 'PAINTING_LIST_FAIL'


export const PAINTING_DETAILS_REQUEST = 'PAINTING_DETAILS_REQUEST'
export const PAINTING_DETAILS_SUCCESS = 'PAINTING_DETAILS_SUCCESS'
export const PAINTING_DETAILS_FAIL = 'PAINTING_DETAILS_FAIL'


export const PAINTING_DELETE_REQUEST = 'PAINTING_DELETE_REQUEST'
export const PAINTING_DELETE_SUCCESS = 'PAINTING_DELETE_SUCCESS'
export const PAINTING_DELETE_FAIL = 'PAINTING_DELETE_FAIL'

export const PAINTING_CREATE_REQUEST = 'PAINTING_CREATE_REQUEST'
export const PAINTING_CREATE_SUCCESS = 'PAINTING_CREATE_SUCCESS'
export const PAINTING_CREATE_FAIL = 'PAINTING_CREATE_FAIL'
export const PAINTING_CREATE_RESET = 'PAINTING_CREATE_RESET'


export const PAINTING_UPDATE_REQUEST = 'PAINTING_UPDATE_REQUEST'
export const PAINTING_UPDATE_SUCCESS = 'PAINTING_UPDATE_SUCCESS'
export const PAINTING_UPDATE_FAIL = 'PAINTING_UPDATE_FAIL'
export const PAINTING_UPDATE_RESET = 'PAINTING_UPDATE_RESET'


export const PAINTING_CREATE_REVIEW_REQUEST = 'PAINTING_CREATE_REVIEW_REQUEST'
export const PAINTING_CREATE_REVIEW_SUCCESS = 'PAINTING_CREATE_REVIEW_SUCCESS'
export const PAINTING_CREATE_REVIEW_FAIL = 'PAINTING_CREATE_REVIEW_FAIL'
export const PAINTING_CREATE_REVIEW_RESET = 'PAINTING_CREATE_REVIEW_RESET'

export const PAINTING_TOP_REQUEST = 'PAINTING_TOP_REQUEST'
export const PAINTING_TOP_SUCCESS = 'PAINTING_TOP_SUCCESS'
export const PAINTING_TOP_FAIL = 'PAINTING_TOP_FAIL'


