# Generated by Django 4.0.3 on 2022-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_painting_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
    ]
