# Generated by Django 4.0.3 on 2022-04-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_painting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('name', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.painting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
