const paintings = [
  {
    '_id': '1',
    'name': 'Playng Light Empire',
    'image': '/images/playing_light.jpg',
    'description':
      'Hommage On Empire of Light',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '60 cm',
    'year': '2021',
    'price': 89.99,
    'available': true,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Last sunny day',
    'image': '/images/sunny_day.jpg',
    'description':
      'Autumn sunny day',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '60 cm',
    'year': '2021',
    'price': 49.99,
    'available': true,
    'rating': 4.5,
    'numReviews': 12,
  },

  {
    '_id': '3',
    'name': 'Baltic See',
    'image': '/images/baltic_sea.jpg',
    'description':
      'I painted this painting to commemorate the day my father was barried',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '50 cm',
    'year': '2021',
    'price': 49.99,
    'available': true,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Dots',
    'image': '/images/dots.jpg',
    'description':
      'The house I was born in',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '50 cm',
    'year': '2021',
    'price': 89.99,
    'available': true,
    'rating': 4.0,
    'numReviews': 11,
  },
  {
    '_id': '5',
    'name': 'Night',
    'image': '/images/night.jpg',
    'description':
      'Road',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '60 cm',
    'year': '2021',
    'price': 89.99,
    'available': false,
    'rating': 0.5,
    'numReviews': 1,
  },
  {
    '_id': '6',
    'name': 'Light',
    'image': '/images/light.jpg',
    'description':
      'Road',
    'materials': 'Acryl on Canvas stretcher bar',
    'height': '50 cm',
    'widht': '50 cm',
    'year': '2021',
    'price': 69.99,
    'available': false,
    'rating': 0.5,
    'numReviews': 1,
  },
]
 

export default paintings
